name = "current"
description = "Tabs: agent; review; git; terminal"
cwd = "current"

[[tabs]]
name = "agent"
command = "oc"

[[tabs]]
name = "git"
command = "git sss"

[[tabs]]
name = "review"
command = "hunk show"

[[tabs]]
name = "terminal"
